openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/NiekRoelofs/Project2.4G1/1.0.0
info:
  version: 1.0.0
  title: Bank
  description: 'Bank API for project 2.4'
paths: 
  /example:
    get:
      tags:
        - example
      summary: example
      operationId: example
      description: example
      responses:
        '200': 
          description: example
  /api/user?id=id: #id is needed for employee on GET, PUT and DELETE
    get:
      tags:
        - user
      summary: Get user information
      operationId: getUser
      description: Returns the following user information from the bank user, this can be a client or an employee; id, first name, last name, email,
                    phone number, address, role, bankaccounts and limits.
      parameters:
        - in: query
          name: id
          schema:
            type: integer
          description: Account id
      responses: 
        '200':
          description: User data
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    put:
      tags:
        - user
      summary: Edit the user information
      operationId: editUser
      requestBody:
        description: The customer can edit their email, phone number and address. The employee can edit all User information.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Edited User
          content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
    delete:
      tags:
        - user
      summary: Delete a User
      operationId: deleteUser
      responses:
        '200':
          description: User has been deleted
    post:
      tags:
        - user
      summary: Create a User
      operationId: createUser
      requestBody:
        description: The employee can create a User while entering all required fields.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Created User
          content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'

  /transaction:
    get:
      tags: [transactions]
      operationId: getTransaction
      summary: Get details of a transaction
      description: Get details of a transaction returned as a JSON. requires a transaction id
      responses:
        '200':
          description: Successfully queried transaction
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/Transaction"  
                  
      parameters: 
        - in: query
          name: id
          schema:
            type: integer
          required: true
          
          
    post:
      tags: [transactions]
      operationId: makeTransaction
      summary: Create a transaction
      description: Creates a transaction from one IBAN to another. Source iban needs to be from customer unless an employee creates a transaction
      responses:
        '200':
          description: Successfully added a transaction

      requestBody:
        description: argument fields
        required: true
        content:
          application/json:
            schema:
              type: object
              required: 
                - IBAN_from
                - IBAN_to
                - amount
                
              properties:
                IBAN_from:
                  type: string
                  example: "IBAN01"
                IBAN_to:
                  type: string
                  example: "IBAN02"
                amount:
                  type: number
                  example: 10.50

                
  '/Bankaccount':
    get:
      tags:
        - Bankaccount
      summary: Get bankaccount information
      operationId: getBankaccount
      description: Calling this allows you to get all your bankaccount information based on the id
      parameters:
        - name: id
          in: query
          description: ID of bankaccount to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: operation succesful
        '400':
          description: bad input parameter
        '404':
          description: bankaccount not found
    post:
      tags:
        - Bankaccount
      summary: create a bankaccount
      operationId: createBankaccount
      requestBody:
        description: Create a bankaccount, this option is employee only
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBankaccount'
      responses:
        '200':
          description: operation succesful
        '400':
          description: bad input parameter
    put:
      tags:
        - Bankaccount
      summary: make the money flows happen
      operationId: completeMoneyFlow
      requestBody:
        description: Complete a deposit or withdraw as an employee
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BankaccountMoneyFlow'
      responses:
        '200':
          description: operation succesful
        '400':
          description: bad input parameter
        '404':
          description: IBAN not found
        
components:
  schemas:
    User:
      type: object
      required:
       - id
       - FirstName
       - LastName
       - Email
       - PhoneNumber
       - Address
       - Role
       - BankAccounts
       - Limits
      properties:
        id:
          type: integer
          example: 1
        FirstName: 
          type: string
          example: "James"
        LastName:
          type: string
          example: "Ford"
        Email:
          type: string
          exampe: "james@email.com"
        PhoneNumber:
          type: string
          example: "+31 6 12345678"
        Address:
          $ref: '#/components/schemas/Address'
        Role:
          type: string
          enum: [Customer, Employee]
          example: "Customer"
        BankAccounts:
          type: array
          items:
            $ref: '#/components/schemas/BankAccount'
        Limits:
          type: array
          items:
            $ref: '#/components/schemas/Limit'
    Address:
      type: object
      required:
       - street
       - houseNumber
       - postalcode
       - city
       - country
      properties:
        street:
          type: string
          example: "Long Road"
        houseNumber:
          type: integer
          example: 10
        postalcode:
          type: string
          example: "1234AB"
        city:
          type: string
          example: "Big City"
        country:
          type: string
          example: "Wakanda"
    BankAccount:
      type: object
      required:
       - name
       - id
       - accountType
       - IBAN
       - amount
      properties:
        name:
          type: string
          example: "Daily Account"
        id:
          type: integer
          example: 1
        accountType:
          type: string
          enum: [Current, Savings]
          example: "Current"
        IBAN:
          type: string
          example: NL20RABO124235346
        amount:
          type: number
          example: 1200
    Limit:
      type: object
      required:
       - name
       - limit
       - current
      properties:
        name:
          type: string
          example: "AbsoluteLimit"
        limit:
          type: number
          example: 1000
        current:
          type: number
          example: 100
    CreateBankaccount:
      type: object
      required:
        - Type
      properties:
        Type:
          type: string
          enum: [Current, Savings]
    BankaccountMoneyFlow:
      type: object
      required:
        - IBAN
        - Type
        - Amount
      properties:
        IBAN:
          type: string
        Type:
          type: string
        Amount:
          type: integer
    Transaction:
      type: object
      required:
        - id
        - type 
        - timestamp
        - IBAN_from
        - IBAN_to
        - performed_by
        - amount
      properties:
        id:
          type: integer
          minimum: 0
          example: 10
        type:
          type: string
          enum: [Transaction, Deposit, Withdraw]
          example: "Transaction"
        timestamp:
          type: string
          format: date-time
          example: "2015-07-20T15:49:04-07:00"
        IBAN_from:
          type: string
          example: "IBAN01"
        IBAN_to:
          type: string
          example: "IBAN02"
        performed_by:
          type: object
          required: 
            - name
            - role
          properties:
            name:
              type: string
              example: "Owen"
            role:
              type: string
              enum: [Customer, Employee]
              example: "Customer"
        amount:
          type: number
          example: 10

